--
-- File generated with SQLiteStudio v3.4.4 on sex fev 16 09:17:28 2024
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: babylon_glossario
DROP TABLE IF EXISTS babylon_glossario;
CREATE TABLE IF NOT EXISTS babylon_glossario (id_glossario INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, nm_arquivo TEXT NOT NULL, nm_glossario TEXT NOT NULL, ds_glossario TEXT, dt_criacao DATETIME, dt_carga DATETIME DEFAULT (CURRENT_TIMESTAMP), id_situacao INTEGER NOT NULL CONSTRAINT fk_babylon_situacao_glossario REFERENCES babylon_glossario_situacao (id_situacao) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, id_categoria INTEGER NOT NULL CONSTRAINT fk_babylon_categoria_glossario REFERENCES babylon_glossario_categoria (id_categoria) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, qt_tempoextracao FLOAT NOT NULL DEFAULT (0.0), qt_totalregistros INTEGER, qt_totalregistrosignorar INTEGER, id_carga INTEGER DEFAULT (0), id_idiomaorigem INTEGER NOT NULL CONSTRAINT fk_babylon_idioma_origem REFERENCES babylon_glossario_idioma (id_idioma) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, id_idiomadestino INTEGER NOT NULL CONSTRAINT fk_babylon_idioma_destino REFERENCES babylon_glossario_idioma (id_idioma) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, dt_atualizacao DATETIME, id_autor INTEGER CONSTRAINT fk_babylon_glossario_autor REFERENCES babylon_glossario_autor (id_autor) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH SIMPLE DEFERRABLE INITIALLY DEFERRED NOT NULL, qt_totalarquivos INTEGER DEFAULT (0), qt_tempocargaarquivos FLOAT DEFAULT (0), bo_processado INTEGER DEFAULT (0) NOT NULL, qt_tempocarga FLOAT DEFAULT (0.0) NOT NULL, qt_tempoconversao FLOAT NOT NULL DEFAULT (0.0));

-- Table: babylon_glossario_autor
DROP TABLE IF EXISTS babylon_glossario_autor;
CREATE TABLE IF NOT EXISTS babylon_glossario_autor (id_autor INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, nm_autor TEXT NOT NULL CONSTRAINT uk_babylon_autor UNIQUE ON CONFLICT ROLLBACK);
INSERT INTO babylon_glossario_autor (id_autor, nm_autor) VALUES (1, '?');

-- Table: babylon_glossario_categoria
DROP TABLE IF EXISTS babylon_glossario_categoria;
CREATE TABLE IF NOT EXISTS babylon_glossario_categoria (id_categoria INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, nm_categoria TEXT NOT NULL CONSTRAINT uk_babylon_categoria UNIQUE ON CONFLICT ROLLBACK, bo_premium INTEGER DEFAULT (0));
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (1, 'Languages & Translation', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (2, 'Languages & Translation - Afrikaans', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (3, 'Languages & Translation - Albanian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (4, 'Languages & Translation - American Indian Languages', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (5, 'Languages & Translation - Amharic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (6, 'Languages & Translation - Ancient Languages', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (7, 'Languages & Translation - Arabic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (8, 'Languages & Translation - Aromanian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (9, 'Languages & Translation - Azerbaijani', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (10, 'Languages & Translation - Babylon', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (11, 'Languages & Translation - Basque', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (12, 'Languages & Translation - Bosnian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (13, 'Languages & Translation - Bulgarian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (14, 'Languages & Translation - Castilian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (15, 'Languages & Translation - Catalan', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (16, 'Languages & Translation - Celtic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (17, 'Languages & Translation - Chamorro', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (18, 'Languages & Translation - Chinese', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (19, 'Languages & Translation - Circassian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (20, 'Languages & Translation - Croatian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (21, 'Languages & Translation - Czech', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (22, 'Languages & Translation - Danish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (23, 'Languages & Translation - Dialects', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (24, 'Languages & Translation - Dutch', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (25, 'Languages & Translation - English', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (26, 'Languages & Translation - Esperanto', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (27, 'Languages & Translation - Estonian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (28, 'Languages & Translation - Finnish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (29, 'Languages & Translation - Flemish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (30, 'Languages & Translation - French', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (31, 'Languages & Translation - Galician', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (32, 'Languages & Translation - German', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (33, 'Languages & Translation - Greek', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (34, 'Languages & Translation - Hebrew', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (35, 'Languages & Translation - Hindi', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (36, 'Languages & Translation - Hungarian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (37, 'Languages & Translation - Icelandic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (38, 'Languages & Translation - Indonesian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (39, 'Languages & Translation - Interlingua', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (40, 'Languages & Translation - Interlingue', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (41, 'Languages & Translation - Invented', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (42, 'Languages & Translation - Italian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (43, 'Languages & Translation - Japanese', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (44, 'Languages & Translation - Korean', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (45, 'Languages & Translation - Kurdish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (46, 'Languages & Translation - Latin', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (47, 'Languages & Translation - Latvian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (48, 'Languages & Translation - Lithuanian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (49, 'Languages & Translation - Malay', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (50, 'Languages & Translation - Maori', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (51, 'Languages & Translation - Mongolian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (52, 'Languages & Translation - Nauruan', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (53, 'Languages & Translation - Norwegian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (54, 'Languages & Translation - Papiamento', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (55, 'Languages & Translation - Persian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (56, 'Languages & Translation - Polish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (57, 'Languages & Translation - Portuguese', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (58, 'Languages & Translation - Rohingya', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (59, 'Languages & Translation - Romanian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (60, 'Languages & Translation - Romany', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (61, 'Languages & Translation - Runasimi', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (62, 'Languages & Translation - Russian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (63, 'Languages & Translation - Sanskrit', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (64, 'Languages & Translation - Serbian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (65, 'Languages & Translation - Sign Language', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (66, 'Languages & Translation - Slang & Jargon', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (67, 'Languages & Translation - Slovak', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (68, 'Languages & Translation - Slovenian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (69, 'Languages & Translation - Spanish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (70, 'Languages & Translation - Suriname', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (71, 'Languages & Translation - Swabian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (72, 'Languages & Translation - Swahili', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (73, 'Languages & Translation - Swedish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (74, 'Languages & Translation - Tamazight', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (75, 'Languages & Translation - Thai', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (76, 'Languages & Translation - Tibetan', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (77, 'Languages & Translation - Tupi-Guarani', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (78, 'Languages & Translation - Turkic Languages', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (79, 'Languages & Translation - Turkish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (80, 'Languages & Translation - Turkmen', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (81, 'Languages & Translation - Ukrainian', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (82, 'Languages & Translation - Urdu', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (83, 'Languages & Translation - Vietnamese', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (84, 'Languages & Translation - Visayan', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (85, 'Languages & Translation - Yiddish', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (86, 'Languages & Translation - Zulu', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (87, 'Reference', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (88, 'Reference - Acronyms & Abbreviations', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (89, 'Reference - Encyclopedias', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (90, 'Reference - General Dictionaries & Thesauri Dictionaries', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (91, 'Reference - Lists & Directories', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (92, 'Reference - Research', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (93, 'Reference - Statistics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (94, 'Arts & Humanities', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (95, 'Arts & Humanities - Antiques & Collectibles', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (96, 'Arts & Humanities - Books & Literature', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (97, 'Arts & Humanities - Books & Literature - Authors', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (98, 'Arts & Humanities - Books & Literature - Classics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (99, 'Arts & Humanities - Books & Literature - Fiction', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (100, 'Arts & Humanities - Crafts', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (101, 'Arts & Humanities - Dance', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (102, 'Arts & Humanities - Design Arts', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (103, 'Arts & Humanities - Design Arts - Architecture', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (104, 'Arts & Humanities - Design Arts - Fashion Design', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (105, 'Arts & Humanities - Design Arts - Graphic Design', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (106, 'Arts & Humanities - Design Arts - Industrial Design', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (107, 'Arts & Humanities - Design Arts - Interior Design', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (108, 'Arts & Humanities - History', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (109, 'Arts & Humanities - Linguistics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (110, 'Arts & Humanities - Museums & Galleries', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (111, 'Arts & Humanities - Music', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (112, 'Arts & Humanities - Music - Blues', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (113, 'Arts & Humanities - Music - Classical', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (114, 'Arts & Humanities - Music - Country', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (115, 'Arts & Humanities - Music - Electronic & Dance', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (116, 'Arts & Humanities - Music - Ethnic & World', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (117, 'Arts & Humanities - Music - Folk & Acoustic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (118, 'Arts & Humanities - Music - Jazz', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (119, 'Arts & Humanities - Music - New Age', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (120, 'Arts & Humanities - Music - Opera', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (121, 'Arts & Humanities - Music - Rap & Hip-Hop', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (122, 'Arts & Humanities - Music - Religious & Inspirational', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (123, 'Arts & Humanities - Music - Rock & Pop', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (124, 'Arts & Humanities - Music - Soul/R&B', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (125, 'Arts & Humanities - People', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (126, 'Arts & Humanities - Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (127, 'Arts & Humanities - Philosophy - Contemporary Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (128, 'Arts & Humanities - Philosophy - Eastern Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (129, 'Arts & Humanities - Philosophy - Metaphysics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (130, 'Arts & Humanities - Philosophy - Philosophers', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (131, 'Arts & Humanities - Philosophy - Western Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (132, 'Arts & Humanities - Theater', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (133, 'Arts & Humanities - Visual Arts', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (134, 'Arts & Humanities - Visual Arts - Fine Arts', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (135, 'Arts & Humanities - Visual Arts - Photography', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (136, 'Business & Economy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (137, 'Business & Economy - Banking', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (138, 'Business & Economy - Consumer Information', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (139, 'Business & Economy - Consumer Information - Online Shopping', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (140, 'Business & Economy - Currency', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (141, 'Business & Economy - Finance & Investment', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (142, 'Business & Economy - Finance & Investment - Insurance', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (143, 'Business & Economy - Finance & Investment - Mutual Funds', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (144, 'Business & Economy - Finance & Investment - Stocks', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (145, 'Business & Economy - Management & Administration', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (146, 'Business & Economy - Marketing & Advertising', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (147, 'Business & Economy - Real Estate', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (148, 'Business & Economy - Taxes', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (149, 'Business & Economy - Trade & Industry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (150, 'Business & Economy - Trade & Industry - Tools & Materials', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (151, 'Computers & Internet', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (152, 'Computers & Internet - Communications & Networking', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (153, 'Computers & Internet - Computer Jargon', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (154, 'Computers & Internet - Computer Science', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (155, 'Computers & Internet - Games', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (156, 'Computers & Internet - Graphics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (157, 'Computers & Internet - Hardware', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (158, 'Computers & Internet - Internet', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (159, 'Computers & Internet - Internet - Online Shopping', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (160, 'Computers & Internet - Multimedia', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (161, 'Computers & Internet - Software', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (162, 'Premium', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (163, 'Premium - Michaelis', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (164, 'Premium - Signum', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (165, 'Premium - Vox', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (166, 'Premium - Hazon', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (167, 'Premium - Oxford', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (168, 'Premium - Zanichelli', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (169, 'Premium - Larousse', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (170, 'Premium - Devoto-Oli', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (171, 'Education', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (172, 'Education - Clubs & Activities', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (173, 'Education - Financial Aid', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (174, 'Education - Higher Education', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (175, 'Education - Higher Education - Undergraduate', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (176, 'Education - Organizations', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (177, 'Education - Research', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (178, 'Education - Research - Libraries', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (179, 'Education - Special Education', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (180, 'Education - Teaching', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (181, 'Education - Teaching - Aids & Resources', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (182, 'Education - Teaching - Theory & Method', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (183, 'Entertainment', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (184, 'Entertainment -  Books & Literature', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (185, 'Entertainment -  Books & Literature - Authors', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (186, 'Entertainment -  Books & Literature - Classics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (187, 'Entertainment -  Books & Literature - Fiction', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (188, 'Entertainment -  Books & Literature - Journals & Magazines', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (189, 'Entertainment -  Books & Literature - Juvenile Literature', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (190, 'Entertainment -  Books & Literature - Poetry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (191, 'Entertainment -  Books & Literature - Science Fiction & Fantasy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (192, 'Entertainment - Cartoons & Animation', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (193, 'Entertainment - Dance', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (194, 'Entertainment - Food & Drink', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (195, 'Entertainment - Gambling', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (196, 'Entertainment - Humor', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (197, 'Entertainment - Magic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (198, 'Entertainment - Movies & Film', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (199, 'Entertainment - Movies & Film - Science Fiction & Fantasy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (200, 'Entertainment - Music', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (201, 'Entertainment - Music - Blues', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (202, 'Entertainment - Music - Classical', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (203, 'Entertainment - Music - Country', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (204, 'Entertainment - Music - Electronic & Dance', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (205, 'Entertainment - Music - Ethnic & World', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (206, 'Entertainment - Music - Jazz', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (207, 'Entertainment - Music - New Age', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (208, 'Entertainment - Music - Opera', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (209, 'Entertainment - Music - Rap & Hip-Hop', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (210, 'Entertainment - Music - Religious & Inspirational', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (211, 'Entertainment - Music - Rock & Pop', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (212, 'Entertainment - Music - Soul/R&B', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (213, 'Entertainment - People', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (214, 'Entertainment - Radio', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (215, 'Entertainment - Television', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (216, 'Entertainment - Television - Science Fiction & Fantasy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (217, 'Entertainment - Theater', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (218, 'Entertainment - Toys', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (219, 'Premium - hEnglish', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (220, 'Premium - Logman', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (221, 'Premium - Collins', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (222, 'Premium - Roget', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (223, 'Premium - Soules', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (224, 'Premium - WordNet', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (225, 'Premium - WordWeb', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (226, 'Premium - Chambers', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (227, 'Premium - Toelf', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (228, 'Premium - Latvian', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (229, 'Premium - Terus', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (230, 'Premium - Granada University', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (231, 'Premium - Britannica', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (232, 'Premium - Merriam Webster', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (233, 'Premium - Random House Webster', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (234, 'Premium - Shorter Wikitionary', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (235, 'Premium - WinCept', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (236, 'Premium - Cambridge', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (237, 'Premium - Shorter', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (238, 'Premium - Treccani', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (239, 'Government', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (240, 'Government - International Organizations', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (241, 'Government - International Organizations - UN', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (242, 'Government - Law', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (243, 'Government - Military', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (244, 'Government - Military - Weaponry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (245, 'Government - Politics & Political Systems', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (246, 'Government - Taxes', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (247, 'Health', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (248, 'Health - Alternative Medicine', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (249, 'Health - Children''s Health', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (250, 'Health - Conditions & Diseases', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (251, 'Health - Conditions & Diseases - Autoimmune Diseases', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (252, 'Health - Conditions & Diseases - Cancer', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (253, 'Health - Conditions & Diseases - Heart Diseases', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (254, 'Health - Conditions & Diseases - Kidney Diseases', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (255, 'Health - Conditions & Diseases - Metabolic Diseases', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (256, 'Health - Conditions & Diseases - Respiratory Diseases', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (257, 'Health - Disabilities', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (258, 'Health - Fitness', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (259, 'Health - Medicine', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (260, 'Health - Medicine - Cardiology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (261, 'Health - Medicine - Dentistry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (262, 'Health - Medicine - Endocrinology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (263, 'Health - Medicine - Epidemiology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (264, 'Health - Medicine - Gastroenterology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (265, 'Health - Medicine - Geriatrics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (266, 'Health - Medicine - Hematology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (267, 'Health - Medicine - Human Anatomy & Physiology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (268, 'Health - Medicine - Immunology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (269, 'Health - Medicine - Nephrology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (270, 'Health - Medicine - Obstetrics & Gynecology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (271, 'Health - Medicine - Pathology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (272, 'Health - Medicine - Pediatrics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (273, 'Health - Medicine - Psychiatry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (274, 'Health - Medicine - Surgery', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (275, 'Health - Medicine - Toxicology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (276, 'Health - Medicine - Urology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (277, 'Health - Medicine - Veterinary Medicine', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (278, 'Health - Men''s Health', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (279, 'Health - Mental Health', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (280, 'Health - Nutrition & Diet', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (281, 'Health - Nutrition & Diet - Food & Drink', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (282, 'Health - Pharmacy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (283, 'Health - Procedures & Therapies', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (284, 'Health - Sexuality', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (285, 'Health - Substance Abuse', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (286, 'Health - Women''s Health', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (287, 'News & Media', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (288, 'News & Media - Journalism', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (289, 'News & Media - Journals & Magazines', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (290, 'News & Media - Newspapers', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (291, 'News & Media - Radio', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (292, 'News & Media - Television', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (293, 'News & Media - Television - Science Fiction & Fantasy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (294, 'Recreation & Sports', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (295, 'Recreation & Sports - Amusement & Theme Parks', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (296, 'Recreation & Sports - Archery', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (297, 'Recreation & Sports - Equestrian Sports', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (298, 'Recreation & Sports - Fitness', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (299, 'Recreation & Sports - Games', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (300, 'Recreation & Sports - Golf', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (301, 'Recreation & Sports - Hobbies', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (302, 'Recreation & Sports - Home & Garden', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (303, 'Recreation & Sports - Motor Sports', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (304, 'Recreation & Sports - Martial Arts', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (305, 'Recreation & Sports - Outdoor Recreation', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (306, 'Recreation & Sports - Outdoor Recreation - Camping', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (307, 'Recreation & Sports - Outdoor Recreation - Caving', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (308, 'Recreation & Sports - Outdoor Recreation - Fishing', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (309, 'Recreation & Sports - Outdoor Recreation - Hiking & Climbing', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (310, 'Recreation & Sports - Outdoor Recreation - Hunting & Trapping', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (311, 'Recreation & Sports - People', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (312, 'Recreation & Sports - Team Sports', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (313, 'Recreation & Sports - Team Sports - Baseball', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (314, 'Recreation & Sports - Team Sports - Basketball', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (315, 'Recreation & Sports - Team Sports - Football', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (316, 'Recreation & Sports - Team Sports - Hockey', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (317, 'Recreation & Sports - Team Sports - Soccer', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (318, 'Recreation & Sports - Tennis', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (319, 'Recreation & Sports - Track & Field', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (320, 'Recreation & Sports - Travel & Tourism ', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (321, 'Recreation & Sports - Travel & Tourism - Air Travel', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (322, 'Recreation & Sports - Travel & Tourism - Land Travel', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (323, 'Recreation & Sports - Travel & Tourism - Sites & Monuments', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (324, 'Recreation & Sports - Travel & Tourism - Water Travel', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (325, 'Recreation & Sports - Water Sports', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (326, 'Recreation & Sports - Water Sports - Boating & Sailing', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (327, 'Recreation & Sports - Water Sports - Scuba Diving', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (328, 'Recreation & Sports - Water Sports - Surfing & Windsurfing', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (329, 'Recreation & Sports - Water Sports - Swimming', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (330, 'Recreation & Sports - Weightlifting', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (331, 'Recreation & Sports - Wrestling', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (332, 'Premium - Aurélio', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (333, 'Regional', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (334, 'Regional - Africa', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (335, 'Regional - Asia', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (336, 'Regional - Asia - India', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (337, 'Regional - Australia', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (338, 'Regional - Caribbean', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (339, 'Regional - Central America', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (340, 'Regional - Europe', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (341, 'Regional - Middle East', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (342, 'Regional - National Anthems & Flags', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (343, 'Regional - New Zealand', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (344, 'Regional - North America', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (345, 'Regional - North America - Canada', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (346, 'Regional - North America - Mexico', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (347, 'Regional - North America - United States of America', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (348, 'Regional - Oceania', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (349, 'Regional - South America', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (350, 'Science & Technology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (351, 'Science & Technology - Agriculture', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (352, 'Science & Technology - Agriculture - Aquaculture', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (353, 'Science & Technology - Anthropology & Archaeology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (354, 'Science & Technology - Astronomy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (355, 'Science & Technology - Astronomy - Astrophysics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (356, 'Science & Technology - Aviation', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (357, 'Science & Technology - Biology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (358, 'Science & Technology - Biology - Botany', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (359, 'Science & Technology - Biology - Ecology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (360, 'Science & Technology - Biology - Genetics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (361, 'Science & Technology - Biology - Human Anatomy & Physiology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (362, 'Science & Technology - Biology - Zoology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (363, 'Science & Technology - Chemistry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (364, 'Science & Technology - Communications', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (365, 'Science & Technology - Communications - Telecommunications', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (366, 'Science & Technology - Computer Science', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (367, 'Science & Technology - Earth Sciences', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (368, 'Science & Technology - Earth Sciences - Geography', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (369, 'Science & Technology - Earth Sciences - Geology & Geophysics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (370, 'Science & Technology - Earth Sciences - Meteorology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (371, 'Science & Technology - Earth Sciences - Oceanography', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (372, 'Science & Technology - Energy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (373, 'Science & Technology - Energy - Electricity', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (374, 'Science & Technology - Energy - Nuclear', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (375, 'Science & Technology - Energy - Solar', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (376, 'Science & Technology - Engineering', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (377, 'Science & Technology - Engineering - Automotive', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (378, 'Science & Technology - Engineering - Biomedical Engineering', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (379, 'Science & Technology - Engineering - Chemical', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (380, 'Science & Technology - Engineering - Civil', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (381, 'Science & Technology - Engineering - Electrical & Electronic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (382, 'Science & Technology - Engineering - Industrial', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (383, 'Science & Technology - Engineering - Mechanical', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (384, 'Science & Technology - Mathematics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (385, 'Science & Technology - Mathematics - Statistics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (386, 'Science & Technology - Physics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (387, 'Science & Technology - Space', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (388, 'Social Science', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (389, 'Social Science - Anthropology & Archaeology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (390, 'Social Science - Economics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (391, 'Social Science - History', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (392, 'Social Science - History - Medieval', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (393, 'Social Science - History - Modern & Postmodern', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (394, 'Social Science - Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (395, 'Social Science - Philosophy - Contemporary Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (396, 'Social Science - Philosophy - Eastern Philosophy ', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (397, 'Social Science - Philosophy - Metaphysics', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (398, 'Social Science - Philosophy - Philosophers', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (399, 'Social Science - Philosophy - Western Philosophy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (400, 'Social Science - Political Science', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (401, 'Social Science - Psychology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (402, 'Social Science - Sociology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (403, 'Society & Culture', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (404, 'Society & Culture - Animals & Pets', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (405, 'Society & Culture - Community Services', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (406, 'Society & Culture - Community Services - Fire Protection', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (407, 'Society & Culture - Community Services - Law Enforcement', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (408, 'Society & Culture - Community Services - Social Services', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (409, 'Society & Culture - Crime', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (410, 'Society & Culture - Environment & Nature', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (411, 'Society & Culture - Ethnic', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (412, 'Society & Culture - Family', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (413, 'Society & Culture - Fashion & Beauty', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (414, 'Society & Culture - Fashion & Beauty - Clothing & Footwear', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (415, 'Society & Culture - Fashion & Beauty - Jewelry', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (416, 'Society & Culture - Food & Drink ', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (417, 'Society & Culture - Holidays & Events', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (418, 'Society & Culture - Mythology & Folklore', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (419, 'Society & Culture - Philanthropy', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (420, 'Society & Culture - Religion & Spirituality', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (421, 'Society & Culture - Religion & Spirituality - Astrology', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (422, 'Society & Culture - Religion & Spirituality - Buddhism', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (423, 'Society & Culture - Religion & Spirituality - Christianity', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (424, 'Society & Culture - Religion & Spirituality - Hinduism', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (425, 'Society & Culture - Religion & Spirituality - Islam', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (426, 'Society & Culture - Religion & Spirituality - Judaism', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (427, 'Society & Culture - Religion & Spirituality - Occult & Mysticism', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (428, 'Society & Culture - Sexuality', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (429, 'Society & Culture - Slang & Jargon', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (430, 'Society & Culture - Travel & Tourism', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (431, 'Society & Culture - Travel & Tourism - Air Travel', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (432, 'Society & Culture - Travel & Tourism - Countries', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (433, 'Society & Culture - Travel & Tourism - Land Travel', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (434, 'Society & Culture - Travel & Tourism - Sites & Monuments', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (435, 'Society & Culture - Travel & Tourism - Water Travel', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (436, 'Premium - Padonma', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (437, 'Premium - hFarsi', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (438, 'Premium - MacMillan', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (439, 'Ahmad Wadan', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (440, 'Premium - Concise', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (441, 'Premium - Houaiss', 1);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (442, 'NgoNam', 0);
INSERT INTO babylon_glossario_categoria (id_categoria, nm_categoria, bo_premium) VALUES (443, 'Wikipedia', 0);

-- Table: babylon_glossario_erro
DROP TABLE IF EXISTS babylon_glossario_erro;
CREATE TABLE IF NOT EXISTS babylon_glossario_erro (id_erro INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_glossario INTEGER CONSTRAINT fk_babylon_erro_glossario REFERENCES babylon_glossario (id_glossario) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, dt_erro NOT NULL DEFAULT (CURRENT_TIMESTAMP), ds_erro TEXT NOT NULL);

-- Table: babylon_glossario_idioma
DROP TABLE IF EXISTS babylon_glossario_idioma;
CREATE TABLE IF NOT EXISTS babylon_glossario_idioma (id_idioma INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nm_idioma TEXT NOT NULL CONSTRAINT uk_babylon_idioma UNIQUE ON CONFLICT ROLLBACK);
INSERT INTO babylon_glossario_idioma (id_idioma, nm_idioma) VALUES (1, '?');

-- Table: babylon_glossario_situacao
DROP TABLE IF EXISTS babylon_glossario_situacao;
CREATE TABLE IF NOT EXISTS babylon_glossario_situacao (id_situacao INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ds_situacao TEXT NOT NULL);
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (1, 'Esperando para ser(em) carregado(s)');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (2, 'Na fila de carga no momento');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (3, 'Erro de carga');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (4, 'Sem registros');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (5, 'Sem dados na conversão');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (6, 'Carregado(s)');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (7, 'Em carga');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (8, 'Carregado manualmente');
INSERT INTO babylon_glossario_situacao (id_situacao, ds_situacao) VALUES (9, 'Erro no conversor');

-- Table: babylon_glossario_termo
DROP TABLE IF EXISTS babylon_glossario_termo;
CREATE TABLE IF NOT EXISTS babylon_glossario_termo (id_termo INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_glossario INTEGER NOT NULL CONSTRAINT fk_baylon_termo_glossario REFERENCES babylon_glossario (id_glossario) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, te_termo TEXT, ds_termo TEXT);

-- Table: babylon_glossario_termo_arquivos
DROP TABLE IF EXISTS babylon_glossario_termo_arquivos;
CREATE TABLE IF NOT EXISTS babylon_glossario_termo_arquivos (id_arquivo INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, id_glossario INTEGER NOT NULL CONSTRAINT fk_babylon_termo_arquivo_glossario REFERENCES babylon_glossario (id_glossario) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH SIMPLE DEFERRABLE INITIALLY DEFERRED, nm_arquivo TEXT NOT NULL CONSTRAINT fk_babylon_termo_arquivo_termo REFERENCES babylon_glossario_termo (id_termo) ON DELETE RESTRICT ON UPDATE RESTRICT MATCH "FULL" DEFERRABLE INITIALLY DEFERRED, ob_arquivo BLOB NOT NULL);

-- Index: idx_glossario_arquivo
DROP INDEX IF EXISTS idx_glossario_arquivo;
CREATE INDEX IF NOT EXISTS idx_glossario_arquivo ON babylon_glossario (nm_arquivo);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
